//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
using DUT.PACS.Simulator.ServiceDoorControl10;

namespace DUT.PACS.Simulator.ExternalLogging
{
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.onvif.org/simulator/StateReportReceiver", ConfigurationName = "StateReportReceiver.StateReportReceiverSoap")]
    public interface StateReportReceiverSoap
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/simulator/StateReportReceiver/UpdateState", IsOneWay = true)]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DoorState))]
        void UpdateState(UpdateStateRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/simulator/StateReportReceiver/CloseConnection", ReplyAction = "*")]
        CloseConnectionResponse CloseConnection(CloseConnectionRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UpdateStateRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UpdateState", Namespace = "http://www.onvif.org/simulator/StateReportReceiver", Order = 0)]
        public UpdateStateRequestBody Body;

        public UpdateStateRequest()
        {
        }

        public UpdateStateRequest(UpdateStateRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.onvif.org/simulator/StateReportReceiver")]
    public partial class UpdateStateRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string token;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public DoorState state;

        public UpdateStateRequestBody()
        {
        }

        public UpdateStateRequestBody(string Token, DoorState State)
        {
            this.token = Token;
            this.state = State;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface StateReportReceiverSoapChannel : StateReportReceiverSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StateReportReceiverSoapClient : System.ServiceModel.ClientBase<StateReportReceiverSoap>, StateReportReceiverSoap
    {

        public StateReportReceiverSoapClient()
        {
        }

        public StateReportReceiverSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public StateReportReceiverSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StateReportReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StateReportReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void StateReportReceiverSoap.UpdateState(UpdateStateRequest request)
        {
            base.Channel.UpdateState(request);
        }

        public void UpdateState(string token, DoorState state)
        {
            UpdateStateRequest inValue = new UpdateStateRequest();
            inValue.Body = new UpdateStateRequestBody();
            inValue.Body.token = token;
            inValue.Body.state = state;
            ((StateReportReceiverSoap)(this)).UpdateState(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloseConnectionResponse StateReportReceiverSoap.CloseConnection(CloseConnectionRequest request)
        {
            return base.Channel.CloseConnection(request);
        }

        public void CloseConnection()
        {
            CloseConnectionRequest inValue = new CloseConnectionRequest();
            inValue.Body = new CloseConnectionRequestBody();
            CloseConnectionResponse retVal = ((LogReceiverSoap)(this)).CloseConnection(inValue);
        }
    }
}
