//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;

namespace DUT.PACS.Simulator.ExternalLogging
{
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.onvif.org/simulator/logreceiver", ConfigurationName = "LogReceiver.LogReceiverSoap")]
    public interface LogReceiverSoap
    {

        // CODEGEN: Generating message contract since element name message from namespace http://www.onvif.org/simulator/logreceiver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/simulator/logreceiver/LogMessage", IsOneWay = true)]
        void LogMessage(LogMessageRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/simulator/logreceiver/CloseConnection", ReplyAction = "*")]
        CloseConnectionResponse CloseConnection(CloseConnectionRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LogMessageRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "LogMessage", Namespace = "http://www.onvif.org/simulator/logreceiver", Order = 0)]
        public LogMessageRequestBody Body;

        public LogMessageRequest()
        {
        }

        public LogMessageRequest(LogMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.onvif.org/simulator/logreceiver")]
    public partial class LogMessageRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string message;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public MessageType type;

        public LogMessageRequestBody()
        {
        }

        public LogMessageRequestBody(string message, MessageType type)
        {
            this.message = message;
            this.type = type;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LogReceiverSoapChannel : LogReceiverSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LogReceiverSoapClient : System.ServiceModel.ClientBase<LogReceiverSoap>, LogReceiverSoap
    {

        public LogReceiverSoapClient()
        {
        }

        public LogReceiverSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public LogReceiverSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LogReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LogReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LogReceiverSoap.LogMessage(LogMessageRequest request)
        {
            base.Channel.LogMessage(request);
        }

        public void LogMessage(string message, MessageType type)
        {
            LogMessageRequest inValue = new LogMessageRequest();
            inValue.Body = new LogMessageRequestBody();
            inValue.Body.message = message;
            inValue.Body.type = type;
            ((LogReceiverSoap)(this)).LogMessage(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloseConnectionResponse LogReceiverSoap.CloseConnection(CloseConnectionRequest request)
        {
            return base.Channel.CloseConnection(request);
        }

        public void CloseConnection()
        {
            CloseConnectionRequest inValue = new CloseConnectionRequest();
            inValue.Body = new CloseConnectionRequestBody();
            CloseConnectionResponse retVal = ((LogReceiverSoap)(this)).CloseConnection(inValue);
        }
    }
}
