//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;


namespace TestTool.Onvif
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ConfigurationName = "DoorControlPort")]
    public interface DoorControlPort
    {
        [OperationContract(Action = "")]
        void DoNothing();

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorState", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "DoorState")]
        DoorState GetDoorState(string Token);

        // CODEGEN: Parameter 'DoorInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfoList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "DoorInfoList")]
        GetDoorInfoListResponse GetDoorInfoList(GetDoorInfoListRequest request);

        // CODEGEN: Parameter 'DoorInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfoListByTokenList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "DoorInfoList")]
        GetDoorInfoListByTokenListResponse GetDoorInfoListByTokenList(GetDoorInfoListByTokenListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfo", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "DoorInfo")]
        DoorInfo GetDoorInfo(string Token);

        // CODEGEN: Parameter 'AccessTime' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/AccessDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        AccessDoorResponse AccessDoor(AccessDoorRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void LockDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/UnlockDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void UnlockDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/BlockDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void BlockDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void LockDownDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownReleaseDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void LockDownReleaseDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void LockOpenDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenReleaseDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void LockOpenReleaseDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/DoubleLockDoor", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DoubleLockDoor(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetServiceCapabilities", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Capabilities")]
        DoorControlServiceCapabilities GetServiceCapabilities();
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorState
    {

        private DoorModeType doorModeField;

        private DoorMonitorStateType doorMonitorField;

        private DoorLockMonitorStateType doorLockMonitorField;

        private DoorLockMonitorStateType doorDoubleLockMonitorField;

        private bool doorDoubleLockMonitorFieldSpecified;

        private DoorTamperStateType doorTamperField;

        private DoorAlarmStateType doorAlarmField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DoorModeType DoorMode
        {
            get
            {
                return this.doorModeField;
            }
            set
            {
                this.doorModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DoorMonitorStateType DoorMonitor
        {
            get
            {
                return this.doorMonitorField;
            }
            set
            {
                this.doorMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DoorLockMonitorStateType DoorLockMonitor
        {
            get
            {
                return this.doorLockMonitorField;
            }
            set
            {
                this.doorLockMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public DoorLockMonitorStateType DoorDoubleLockMonitor
        {
            get
            {
                return this.doorDoubleLockMonitorField;
            }
            set
            {
                this.doorDoubleLockMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoorDoubleLockMonitorSpecified
        {
            get
            {
                return this.doorDoubleLockMonitorFieldSpecified;
            }
            set
            {
                this.doorDoubleLockMonitorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public DoorTamperStateType DoorTamper
        {
            get
            {
                return this.doorTamperField;
            }
            set
            {
                this.doorTamperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public DoorAlarmStateType DoorAlarm
        {
            get
            {
                return this.doorAlarmField;
            }
            set
            {
                this.doorAlarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 6)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorModeType
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Locked,

        /// <remarks/>
        Unlocked,

        /// <remarks/>
        Accessed,

        /// <remarks/>
        Blocked,

        /// <remarks/>
        LockedDown,

        /// <remarks/>
        LockedOpen,

        /// <remarks/>
        DoubleLocked,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorMonitorStateType
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Open,

        /// <remarks/>
        Closed,

        /// <remarks/>
        NotSupported,

        /// <remarks/>
        Fault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorLockMonitorStateType
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Locked,

        /// <remarks/>
        Unlocked,

        /// <remarks/>
        NotSupported,

        /// <remarks/>
        Fault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorTamperStateType
    {

        /// <remarks/>
        NotSupported,

        /// <remarks/>
        NotInTamper,

        /// <remarks/>
        TamperDetected,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorAlarmStateType
    {

        /// <remarks/>
        Normal,

        /// <remarks/>
        DoorForcedOpen,

        /// <remarks/>
        DoorOpenTooLong,

        /// <remarks/>
        Fault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ServiceCapabilities", Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessControlServiceCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private int maxLimitField;

        private bool disableAccessPointField;

        private bool disableAccessPointFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DisableAccessPoint
        {
            get
            {
                return this.disableAccessPointField;
            }
            set
            {
                this.disableAccessPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisableAccessPointSpecified
        {
            get
            {
                return this.disableAccessPointFieldSpecified;
            }
            set
            {
                this.disableAccessPointFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private bool disableAccessPointField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public AccessPointCapabilities()
        {
            this.disableAccessPointField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool DisableAccessPoint
        {
            get
            {
                return this.disableAccessPointField;
            }
            set
            {
                this.disableAccessPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DataEntity", Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class DataEntity1
    {

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointInfoBase : DataEntity1
    {

        private string nameField;

        private string descriptionField;

        private string areaFromField;

        private string areaToField;

        private bool enabledField;

        private string typeField;

        private string entityField;

        public AccessPointInfoBase()
        {
            this.typeField = "tdc:Door";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string AreaFrom
        {
            get
            {
                return this.areaFromField;
            }
            set
            {
                this.areaFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string AreaTo
        {
            get
            {
                return this.areaToField;
            }
            set
            {
                this.areaToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.ComponentModel.DefaultValueAttribute("tdc:Door")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointInfo : AccessPointInfoBase
    {

        private AccessPointCapabilities capabilitiesField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AccessPointCapabilities Capabilities
        {
            get
            {
                return this.capabilitiesField;
            }
            set
            {
                this.capabilitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AreaInfoBase : DataEntity1
    {

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AreaInfo : AreaInfoBase
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorControlServiceCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private int maxLimitField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class AccessDoorExtension
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorCapabilities
    {

        private bool momentaryAccessField;

        private bool lockField;

        private bool unlockField;

        private bool blockField;

        private bool doubleLockField;

        private bool lockDownField;

        private bool lockOpenField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool MomentaryAccess
        {
            get
            {
                return this.momentaryAccessField;
            }
            set
            {
                this.momentaryAccessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool Lock
        {
            get
            {
                return this.lockField;
            }
            set
            {
                this.lockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool Unlock
        {
            get
            {
                return this.unlockField;
            }
            set
            {
                this.unlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool Block
        {
            get
            {
                return this.blockField;
            }
            set
            {
                this.blockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool DoubleLock
        {
            get
            {
                return this.doubleLockField;
            }
            set
            {
                this.doubleLockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public bool LockDown
        {
            get
            {
                return this.lockDownField;
            }
            set
            {
                this.lockDownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public bool LockOpen
        {
            get
            {
                return this.lockOpenField;
            }
            set
            {
                this.lockOpenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 7)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DataEntity
    {

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorInfoBase : DataEntity
    {

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorInfo : DoorInfoBase
    {

        private DoorCapabilities capabilitiesField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DoorCapabilities Capabilities
        {
            get
            {
                return this.capabilitiesField;
            }
            set
            {
                this.capabilitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetDoorInfoList", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class GetDoorInfoListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 0)]
        public int Limit;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 1)]
        public int Offset;

        public GetDoorInfoListRequest()
        {
        }

        public GetDoorInfoListRequest(int Limit, int Offset)
        {
            this.Limit = Limit;
            this.Offset = Offset;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetDoorInfoListResponse", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class GetDoorInfoListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DoorInfo[] DoorInfoList;

        public GetDoorInfoListResponse()
        {
        }

        public GetDoorInfoListResponse(DoorInfo[] DoorInfoList)
        {
            this.DoorInfoList = DoorInfoList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetDoorInfoListByTokenList", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class GetDoorInfoListByTokenListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Token", IsNullable = false)]
        public string[] TokenList;

        public GetDoorInfoListByTokenListRequest()
        {
        }

        public GetDoorInfoListByTokenListRequest(string[] TokenList)
        {
            this.TokenList = TokenList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetDoorInfoListByTokenListResponse", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class GetDoorInfoListByTokenListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DoorInfo[] DoorInfoList;

        public GetDoorInfoListByTokenListResponse()
        {
        }

        public GetDoorInfoListByTokenListResponse(DoorInfo[] DoorInfoList)
        {
            this.DoorInfoList = DoorInfoList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AccessDoor", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class AccessDoorRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 0)]
        public string Token;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 1)]
        public bool UseExtendedTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string AccessTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string OpenTooLongTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string PreAlarmTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Order = 5)]
        public AccessDoorExtension Extension;

        public AccessDoorRequest()
        {
        }

        public AccessDoorRequest(string Token, bool UseExtendedTime, string AccessTime, string OpenTooLongTime, string PreAlarmTime, AccessDoorExtension Extension)
        {
            this.Token = Token;
            this.UseExtendedTime = UseExtendedTime;
            this.AccessTime = AccessTime;
            this.OpenTooLongTime = OpenTooLongTime;
            this.PreAlarmTime = PreAlarmTime;
            this.Extension = Extension;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AccessDoorResponse", WrapperNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", IsWrapped = true)]
    public partial class AccessDoorResponse
    {

        public AccessDoorResponse()
        {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoorControlPortChannel : DoorControlPort, System.ServiceModel.IClientChannel
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", ConfigurationName = "PACSPort")]
    public interface PACSPort
    {

        [OperationContract(Action = "")]
        void DoNothing();

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaInfo", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AreaInfo")]
        AreaInfo GetAreaInfo(string Token);

        // CODEGEN: Parameter 'AreaInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaInfoList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AreaInfoList")]
        GetAreaInfoListResponse GetAreaInfoList(GetAreaInfoListRequest request);

        // CODEGEN: Parameter 'AreaInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaInfoListByTokenList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AreaInfoList")]
        GetAreaInfoListByTokenListResponse GetAreaInfoListByTokenList(GetAreaInfoListByTokenListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointInfo", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AccessPointInfo")]
        AccessPointInfo GetAccessPointInfo(string Token);

        // CODEGEN: Parameter 'AccessPointInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointInfoList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AccessPointInfoList")]
        GetAccessPointInfoListResponse GetAccessPointInfoList(GetAccessPointInfoListRequest request);

        // CODEGEN: Parameter 'AccessPointInfoList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointInfoListByTokenList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AccessPointInfoList")]
        GetAccessPointInfoListByTokenListResponse GetAccessPointInfoListByTokenList(GetAccessPointInfoListByTokenListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/EnableAccessPoint", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void EnableAccessPoint(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/DisableAccessPoint", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DisableAccessPoint(string Token);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.onvif.org/ver10/accesscontrol/wsdl/GetServiceCapabilities", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Capabilities")]
        AccessControlServiceCapabilities GetServiceCapabilities();
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAreaInfoList", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAreaInfoListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        public int Limit;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 1)]
        public int Offset;

        public GetAreaInfoListRequest()
        {
        }

        public GetAreaInfoListRequest(int Limit, int Offset)
        {
            this.Limit = Limit;
            this.Offset = Offset;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAreaInfoListResponse", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAreaInfoListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public AreaInfo[] AreaInfoList;

        public GetAreaInfoListResponse()
        {
        }

        public GetAreaInfoListResponse(AreaInfo[] AreaInfoList)
        {
            this.AreaInfoList = AreaInfoList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAreaInfoListByTokenList", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAreaInfoListByTokenListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Token", IsNullable = false)]
        public string[] TokenList;

        public GetAreaInfoListByTokenListRequest()
        {
        }

        public GetAreaInfoListByTokenListRequest(string[] TokenList)
        {
            this.TokenList = TokenList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAreaInfoListByTokenListResponse", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAreaInfoListByTokenListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public AreaInfo[] AreaInfoList;

        public GetAreaInfoListByTokenListResponse()
        {
        }

        public GetAreaInfoListByTokenListResponse(AreaInfo[] AreaInfoList)
        {
            this.AreaInfoList = AreaInfoList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccessPointInfoList", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAccessPointInfoListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        public int Limit;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 1)]
        public int Offset;

        public GetAccessPointInfoListRequest()
        {
        }

        public GetAccessPointInfoListRequest(int Limit, int Offset)
        {
            this.Limit = Limit;
            this.Offset = Offset;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccessPointInfoListResponse", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAccessPointInfoListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public AccessPointInfo[] AccessPointInfoList;

        public GetAccessPointInfoListResponse()
        {
        }

        public GetAccessPointInfoListResponse(AccessPointInfo[] AccessPointInfoList)
        {
            this.AccessPointInfoList = AccessPointInfoList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccessPointInfoListByTokenList", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAccessPointInfoListByTokenListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Token", IsNullable = false)]
        public string[] TokenList;

        public GetAccessPointInfoListByTokenListRequest()
        {
        }

        public GetAccessPointInfoListByTokenListRequest(string[] TokenList)
        {
            this.TokenList = TokenList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAccessPointInfoListByTokenListResponse", WrapperNamespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped = true)]
    public partial class GetAccessPointInfoListByTokenListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.onvif.org/ver10/accesscontrol/wsdl", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public AccessPointInfo[] AccessPointInfoList;

        public GetAccessPointInfoListByTokenListResponse()
        {
        }

        public GetAccessPointInfoListByTokenListResponse(AccessPointInfo[] AccessPointInfoList)
        {
            this.AccessPointInfoList = AccessPointInfoList;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PACSPortChannel : PACSPort, System.ServiceModel.IClientChannel
    {
    }

}