//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.18020.
// 

namespace DUT.CameraWebService.Provisioning10
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Web.Services.WebServiceAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ProvisioningBinding", Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public abstract partial class ProvisioningServiceBinding : Base.BaseDutService
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/GetServiceCapabilities", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Capabilities")]
        public abstract Capabilities GetServiceCapabilities();

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/PanMove", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void PanMove(string VideoSource, PanDirection Direction, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Timeout);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/TiltMove", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void TiltMove(string VideoSource, TiltDirection Direction, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Timeout);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/ZoomMove", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void ZoomMove(string VideoSource, ZoomDirection Direction, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Timeout);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/RollMove", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void RollMove(string VideoSource, RollDirection Direction, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Timeout);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/FocusMove", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void FocusMove(string VideoSource, FocusDirection Direction, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Timeout);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/Stop", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void Stop(string VideoSource);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/provisioning/wsdl/Usage", RequestNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/provisioning/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Usage")]
        public abstract Usage GetUsage(string VideoSource);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public partial class Capabilities
    {

        private string defaultTimeoutField;

        private SourceCapabilities[] sourceField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string DefaultTimeout
        {
            get
            {
                return this.defaultTimeoutField;
            }
            set
            {
                this.defaultTimeoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public SourceCapabilities[] Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public partial class SourceCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private string videoSourceTokenField;

        private string maximumPanMovesField;

        private string maximumTiltMovesField;

        private string maximumZoomMovesField;

        private string maximumRollMovesField;

        private bool autoLevelField;

        private bool autoLevelFieldSpecified;

        private string maximumFocusMovesField;

        private bool autoFocusField;

        private bool autoFocusFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VideoSourceToken
        {
            get
            {
                return this.videoSourceTokenField;
            }
            set
            {
                this.videoSourceTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string MaximumPanMoves
        {
            get
            {
                return this.maximumPanMovesField;
            }
            set
            {
                this.maximumPanMovesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string MaximumTiltMoves
        {
            get
            {
                return this.maximumTiltMovesField;
            }
            set
            {
                this.maximumTiltMovesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string MaximumZoomMoves
        {
            get
            {
                return this.maximumZoomMovesField;
            }
            set
            {
                this.maximumZoomMovesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string MaximumRollMoves
        {
            get
            {
                return this.maximumRollMovesField;
            }
            set
            {
                this.maximumRollMovesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AutoLevel
        {
            get
            {
                return this.autoLevelField;
            }
            set
            {
                this.autoLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoLevelSpecified
        {
            get
            {
                return this.autoLevelFieldSpecified;
            }
            set
            {
                this.autoLevelFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string MaximumFocusMoves
        {
            get
            {
                return this.maximumFocusMovesField;
            }
            set
            {
                this.maximumFocusMovesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AutoFocus
        {
            get
            {
                return this.autoFocusField;
            }
            set
            {
                this.autoFocusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoFocusSpecified
        {
            get
            {
                return this.autoFocusFieldSpecified;
            }
            set
            {
                this.autoFocusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public partial class Usage
    {

        private string panField;

        private string tiltField;

        private string zoomField;

        private string rollField;

        private string focusField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Tilt
        {
            get
            {
                return this.tiltField;
            }
            set
            {
                this.tiltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Zoom
        {
            get
            {
                return this.zoomField;
            }
            set
            {
                this.zoomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Roll
        {
            get
            {
                return this.rollField;
            }
            set
            {
                this.rollField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Focus
        {
            get
            {
                return this.focusField;
            }
            set
            {
                this.focusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public enum PanDirection
    {

        /// <remarks/>
        Left,

        /// <remarks/>
        Right,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public enum TiltDirection
    {

        /// <remarks/>
        Up,

        /// <remarks/>
        Down,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public enum ZoomDirection
    {

        /// <remarks/>
        Wide,

        /// <remarks/>
        Telephoto,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public enum RollDirection
    {

        /// <remarks/>
        Clockwise,

        /// <remarks/>
        Counterclockwise,

        /// <remarks/>
        Auto,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/provisioning/wsdl")]
    public enum FocusDirection
    {

        /// <remarks/>
        Near,

        /// <remarks/>
        Far,

        /// <remarks/>
        Auto,
    }
}