///////////////////////////////////////////////////////////////////////////
//!  @author        Alexander Ryltsov
////

import "oaidl.idl";
import "ocidl.idl";


import "axcore.idl";
import "devenum.idl";
import "axextend.idl";

[
  uuid(6B2DF008-ADE8-47a9-8EAB-AEAB48F631CB),
  object
]
interface ITestControl: IUnknown
{
  HRESULT RunSequence(int Sequence);
  HRESULT RunStep(int Step);
  HRESULT GetActivity(int *Activity);
  HRESULT StopActivity();
  HRESULT GetEvents(LPOLESTR *EventText);
};

/*
// {C82EFDBB-F93D-42f4-AE61-288FBAA90C9B}
DEFINE_GUID(<<name>>, 
0xc82efdbb, 0xf93d, 0x42f4, 0xae, 0x61, 0x28, 0x8f, 0xba, 0xa9, 0xc, 0x9b);
*/

[
  uuid(C82EFDBB-F93D-42f4-AE61-288FBAA90C9B),
  helpstring("Library ONVIF RTSP Filter 15.06")
]
library ONVIFRTSPFilter
{
  [
    uuid(F37C8D57-E7F1-41b9-98D3-D98FAE3618D8),
    helpstring("ONVIF RTSP Filter 15.06")
  ]
  coclass ONVIFRTSPFilter
  {
    [default] interface IFileSourceFilter;
    interface ITestControl;
  }

};