//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTool.Tests.TestCases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTool.Tests.TestCases.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different analytics.
        /// </summary>
        internal static string ConfigsDiffAnalytics_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffAnalytics_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different AnalyticsSpecified flags.
        /// </summary>
        internal static string ConfigsDiffAnalyticsSpecifieds_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffAnalyticsSpecifieds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different bitrates.
        /// </summary>
        internal static string ConfigsDiffBitrates_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffBitrates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different encodings.
        /// </summary>
        internal static string ConfigsDiffEncodings_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffEncodings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different event subscriptions.
        /// </summary>
        internal static string ConfigsDiffEventSubscriptions_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffEventSubscriptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different extensions.
        /// </summary>
        internal static string ConfigsDiffExtensions_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffExtensions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different H264 configurations.
        /// </summary>
        internal static string ConfigsDiffH264Configs_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffH264Configs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different MPEG4 configurations.
        /// </summary>
        internal static string ConfigsDiffMPEG4Configs_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffMPEG4Configs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different multicast configurations.
        /// </summary>
        internal static string ConfigsDiffMulticastConfigs_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffMulticastConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different names.
        /// </summary>
        internal static string ConfigsDiffNames_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffNames_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different PTZ statuses.
        /// </summary>
        internal static string ConfigsDiffPTZStatuses_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffPTZStatuses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different qualities.
        /// </summary>
        internal static string ConfigsDiffQualities_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffQualities_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different video resolutions.
        /// </summary>
        internal static string ConfigsDiffResolutions_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffResolutions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different sample rates.
        /// </summary>
        internal static string ConfigsDiffSampleRates_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffSampleRates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different session timeouts.
        /// </summary>
        internal static string ConfigsDiffSessionTimeouts_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffSessionTimeouts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different source tokens.
        /// </summary>
        internal static string ConfigsDiffSourceTokens_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffSourceTokens_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different tokens.
        /// </summary>
        internal static string ConfigsDiffTokens_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffTokens_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurations have different rate controls.
        /// </summary>
        internal static string ConfigsDiffVideoRateControls_Text {
            get {
                return ResourceManager.GetString("ConfigsDiffVideoRateControls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encoder configurations are not equal: {0}.
        /// </summary>
        internal static string ErrorAudioEncoderConfigNotEqual_Format {
            get {
                return ResourceManager.GetString("ErrorAudioEncoderConfigNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio source configurations are not equal: {0}.
        /// </summary>
        internal static string ErrorAudioSourceConfigNotEqual_Format {
            get {
                return ResourceManager.GetString("ErrorAudioSourceConfigNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid H.264 video encoder configuration options.
        /// </summary>
        internal static string ErrorH264VideoEncoderConfigOptions_Text {
            get {
                return ResourceManager.GetString("ErrorH264VideoEncoderConfigOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic space is missing or incorrect.
        /// </summary>
        internal static string ErrorIncorrectGenericSpace {
            get {
                return ResourceManager.GetString("ErrorIncorrectGenericSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type is not {0} with namespace {1}.
        /// </summary>
        internal static string ErrorIncorrectTypes_Format {
            get {
                return ResourceManager.GetString("ErrorIncorrectTypes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio encoder configuration options returned by the DUT.
        /// </summary>
        internal static string ErrorInvalidAudioEncoderConfigOptions_Text {
            get {
                return ResourceManager.GetString("ErrorInvalidAudioEncoderConfigOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PTZ status returned by the DUT.
        /// </summary>
        internal static string ErrorInvalidPTZStatus {
            get {
                return ResourceManager.GetString("ErrorInvalidPTZStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device entry point has invalid path. Expected /onvif/device_service - Actual {0}.
        /// </summary>
        internal static string ErrorInvalidServicePath_Format {
            get {
                return ResourceManager.GetString("ErrorInvalidServicePath_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProbeMatch XAddrs contains invalid address {0}.
        /// </summary>
        internal static string ErrorInvalidXAddrs_Format {
            get {
                return ResourceManager.GetString("ErrorInvalidXAddrs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JPEG video encoder configuration options.
        /// </summary>
        internal static string ErrorJpegVideoEncoderConfigOptions_Text {
            get {
                return ResourceManager.GetString("ErrorJpegVideoEncoderConfigOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata configurations are not equal: {0}.
        /// </summary>
        internal static string ErrorMetadataConfigNotEqual_Format {
            get {
                return ResourceManager.GetString("ErrorMetadataConfigNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory scope {0} is missing.
        /// </summary>
        internal static string ErrorMissingMandatoryScope_Format {
            get {
                return ResourceManager.GetString("ErrorMissingMandatoryScope_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope {0} is missing.
        /// </summary>
        internal static string ErrorMissingScope_Format {
            get {
                return ResourceManager.GetString("ErrorMissingScope_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MPEG4 video encoder configuration options.
        /// </summary>
        internal static string ErrorMpeg4VideoEncoderConfigOptions_Text {
            get {
                return ResourceManager.GetString("ErrorMpeg4VideoEncoderConfigOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created media profile contains configuration entities.
        /// </summary>
        internal static string ErrorNewProfileNotEmpty_Text {
            get {
                return ResourceManager.GetString("ErrorNewProfileNotEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio encoder with AAC encoding support.
        /// </summary>
        internal static string ErrorNoAACAudioEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoAACAudioEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio encoder configurations retuned by the DUT.
        /// </summary>
        internal static string ErrorNoAudioEncoderConfigs_Text {
            get {
                return ResourceManager.GetString("ErrorNoAudioEncoderConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio source configurations retuned by the DUT.
        /// </summary>
        internal static string ErrorNoAudioSourceConfigs_Text {
            get {
                return ResourceManager.GetString("ErrorNoAudioSourceConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio sources returned by the DUT.
        /// </summary>
        internal static string ErrorNoAudioSources_Text {
            get {
                return ResourceManager.GetString("ErrorNoAudioSources_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to receive Bye message.
        /// </summary>
        internal static string ErrorNoByeMessage_Text {
            get {
                return ResourceManager.GetString("ErrorNoByeMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not contain &lt;EndpointReference&gt; element.
        /// </summary>
        internal static string ErrorNoEndpointReference_Text {
            get {
                return ResourceManager.GetString("ErrorNoEndpointReference_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio encoder with G.711 encoding support.
        /// </summary>
        internal static string ErrorNoG711AudioEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoG711AudioEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio encoder with G.726 encoding support.
        /// </summary>
        internal static string ErrorNoG726AudioEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoG726AudioEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video encoder with H.264 encoding support.
        /// </summary>
        internal static string ErrorNoH264VideoEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoH264VideoEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to receive Hello message.
        /// </summary>
        internal static string ErrorNoHelloMessage_Text {
            get {
                return ResourceManager.GetString("ErrorNoHelloMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video encoder with JPEG encoding support.
        /// </summary>
        internal static string ErrorNoJpegVideoEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoJpegVideoEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media service address returned by the DUT.
        /// </summary>
        internal static string ErrorNoMediaAddress_Text {
            get {
                return ResourceManager.GetString("ErrorNoMediaAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media profiles returned by the DUT.
        /// </summary>
        internal static string ErrorNoMediaProfiles_Text {
            get {
                return ResourceManager.GetString("ErrorNoMediaProfiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No metadata configurations retuned by the DUT.
        /// </summary>
        internal static string ErrorNoMetadataConfigs_Text {
            get {
                return ResourceManager.GetString("ErrorNoMetadataConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video encoder with MPEG4 encoding support.
        /// </summary>
        internal static string ErrorNoMPEG4VideoEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoMPEG4VideoEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not contain &lt;ProbeMatch&gt; element.
        /// </summary>
        internal static string ErrorNoProbeMatch_Text {
            get {
                return ResourceManager.GetString("ErrorNoProbeMatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to receive ProbeMatches message.
        /// </summary>
        internal static string ErrorNoProbeResponse_Text {
            get {
                return ResourceManager.GetString("ErrorNoProbeResponse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PTZ service address returned by the DUT.
        /// </summary>
        internal static string ErrorNoPTZAddress_Text {
            get {
                return ResourceManager.GetString("ErrorNoPTZAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DUT should return at least one PTZ configuration.
        /// </summary>
        internal static string ErrorNoPTZConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoPTZConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PTZ configurations returned by the DUT.
        /// </summary>
        internal static string ErrorNoPTZConfigurations_Text {
            get {
                return ResourceManager.GetString("ErrorNoPTZConfigurations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DUT should return at least one PTZ node.
        /// </summary>
        internal static string ErrorNoPTZNode_Text {
            get {
                return ResourceManager.GetString("ErrorNoPTZNode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get PTZ profile.
        /// </summary>
        internal static string ErrorNoPTZProfile {
            get {
                return ResourceManager.GetString("ErrorNoPTZProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not contain &lt;Scopes&gt; element.
        /// </summary>
        internal static string ErrorNoScopes_Text {
            get {
                return ResourceManager.GetString("ErrorNoScopes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Scopes&gt; does not contain &lt;Text&gt; element.
        /// </summary>
        internal static string ErrorNoScopesText_Text {
            get {
                return ResourceManager.GetString("ErrorNoScopesText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not contain &lt;Types&gt; element.
        /// </summary>
        internal static string ErrorNoTypes_Text {
            get {
                return ResourceManager.GetString("ErrorNoTypes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video encoder configuration does not contain valid jpeg enconding options.
        /// </summary>
        internal static string ErrorNoValidJpegOptions_Text {
            get {
                return ResourceManager.GetString("ErrorNoValidJpegOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile with video source and video encoder configuration found.
        /// </summary>
        internal static string ErrorNoValidMediaProfile_Text {
            get {
                return ResourceManager.GetString("ErrorNoValidMediaProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video encoder configuration in profile.
        /// </summary>
        internal static string ErrorNoVideoEncoderConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoVideoEncoderConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video encoder configurations retuned by the DUT.
        /// </summary>
        internal static string ErrorNoVideoEncoderConfigs_Text {
            get {
                return ResourceManager.GetString("ErrorNoVideoEncoderConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video source configuration in profile.
        /// </summary>
        internal static string ErrorNoVideoSourceConfig_Text {
            get {
                return ResourceManager.GetString("ErrorNoVideoSourceConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video source configurations retuned by the DUT.
        /// </summary>
        internal static string ErrorNoVideoSourceConfigs_Text {
            get {
                return ResourceManager.GetString("ErrorNoVideoSourceConfigs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video sources returned by the DUT.
        /// </summary>
        internal static string ErrorNoVideoSources_Text {
            get {
                return ResourceManager.GetString("ErrorNoVideoSources_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message does not contain &lt;XAddrs&gt; element.
        /// </summary>
        internal static string ErrorNoXAddrs_Text {
            get {
                return ResourceManager.GetString("ErrorNoXAddrs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one configuration is empty.
        /// </summary>
        internal static string ErrorOneConfigIsEmpty_Text {
            get {
                return ResourceManager.GetString("ErrorOneConfigIsEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PTZ configuration was not saved correctly by the DUT.
        /// </summary>
        internal static string ErrorPTZConfigure_Text {
            get {
                return ResourceManager.GetString("ErrorPTZConfigure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video configurations are not equal: {0}.
        /// </summary>
        internal static string ErrorVideoConfigNotEqual_Format {
            get {
                return ResourceManager.GetString("ErrorVideoConfigNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video encoder configurations are not equal: {0}.
        /// </summary>
        internal static string ErrorVideoEncoderConfigNotEqual_Format {
            get {
                return ResourceManager.GetString("ErrorVideoEncoderConfigNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video encoder configuration token. Expected {0} - Actual {1}.
        /// </summary>
        internal static string ErrorWrongVideoEncoderConfig_Format {
            get {
                return ResourceManager.GetString("ErrorWrongVideoEncoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video source configuration token. Expected {0} - Actual {1}.
        /// </summary>
        internal static string ErrorWrongVideoSourceConfig_Format {
            get {
                return ResourceManager.GetString("ErrorWrongVideoSourceConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTZ configurations are not equal: {0}.
        /// </summary>
        internal static string PTZConfigsNotEqual_Format {
            get {
                return ResourceManager.GetString("PTZConfigsNotEqual_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding audio decoder configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddAudioDecoderConfig_Format {
            get {
                return ResourceManager.GetString("StepAddAudioDecoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding audio encoder configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddAudioEncoderConfig_Format {
            get {
                return ResourceManager.GetString("StepAddAudioEncoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding audio output configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddAudioOutputConfig_Format {
            get {
                return ResourceManager.GetString("StepAddAudioOutputConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding audio source configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddAudioSourceConfig_Format {
            get {
                return ResourceManager.GetString("StepAddAudioSourceConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding metadata configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddMetadataConfig_Format {
            get {
                return ResourceManager.GetString("StepAddMetadataConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding PTZ configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddPTZConfig_Format {
            get {
                return ResourceManager.GetString("StepAddPTZConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding video encoder configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddVideoEncoderConfig_Format {
            get {
                return ResourceManager.GetString("StepAddVideoEncoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding video source configuration [token = &apos;{0}&apos;] to profile [token = &apos;{1}&apos;].
        /// </summary>
        internal static string StepAddVideoSourceConfig_Format {
            get {
                return ResourceManager.GetString("StepAddVideoSourceConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking PTZ capabilities.
        /// </summary>
        internal static string StepCheckPTZCapabilities {
            get {
                return ResourceManager.GetString("StepCheckPTZCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing audio encoder configurations.
        /// </summary>
        internal static string StepCompareAudioEncoderConfigs_Title {
            get {
                return ResourceManager.GetString("StepCompareAudioEncoderConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing audio source configurations.
        /// </summary>
        internal static string StepCompareAudioSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepCompareAudioSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing metadata configurations.
        /// </summary>
        internal static string StepCompareMetadataConfigs_Title {
            get {
                return ResourceManager.GetString("StepCompareMetadataConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing video encoder configurations.
        /// </summary>
        internal static string StepCompareVideoEncoderConfigs_Title {
            get {
                return ResourceManager.GetString("StepCompareVideoEncoderConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing video source configurations.
        /// </summary>
        internal static string StepCompareVideoSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepCompareVideoSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating media profile [name = &apos;{0}&apos;].
        /// </summary>
        internal static string StepCreateMediaProfile_Format {
            get {
                return ResourceManager.GetString("StepCreateMediaProfile_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting media profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepDeleteMediaProfile_Format {
            get {
                return ResourceManager.GetString("StepDeleteMediaProfile_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio encoder configuration.
        /// </summary>
        internal static string StepGetAudioEncoderConfig_Title {
            get {
                return ResourceManager.GetString("StepGetAudioEncoderConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio encoder configuration options for configuration [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetAudioEncoderConfigOptions_Format {
            get {
                return ResourceManager.GetString("StepGetAudioEncoderConfigOptions_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio encoder configuration options.
        /// </summary>
        internal static string StepGetAudioEncoderConfigOptions_Title {
            get {
                return ResourceManager.GetString("StepGetAudioEncoderConfigOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio encoder configurations.
        /// </summary>
        internal static string StepGetAudioEncoderConfigs_Title {
            get {
                return ResourceManager.GetString("StepGetAudioEncoderConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio source configuration.
        /// </summary>
        internal static string StepGetAudioSourceConfig_Title {
            get {
                return ResourceManager.GetString("StepGetAudioSourceConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio source configuration options for configuration [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetAudioSourceConfigOptions_Format {
            get {
                return ResourceManager.GetString("StepGetAudioSourceConfigOptions_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio source configurations.
        /// </summary>
        internal static string StepGetAudioSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepGetAudioSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio sources.
        /// </summary>
        internal static string StepGetAudioSources_Title {
            get {
                return ResourceManager.GetString("StepGetAudioSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio encoder configurations compatible with profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetCompatibleAudioEncoderConfigs_Format {
            get {
                return ResourceManager.GetString("StepGetCompatibleAudioEncoderConfigs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting audio source configurations compatible with profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetCompatibleAudioSourceConfigs_Format {
            get {
                return ResourceManager.GetString("StepGetCompatibleAudioSourceConfigs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting metadata configurations compatible with profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetCompatibleMetadataConfigs_Format {
            get {
                return ResourceManager.GetString("StepGetCompatibleMetadataConfigs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video encoder configurations compatible with profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetCompatibleVideoEncoderConfigs_Format {
            get {
                return ResourceManager.GetString("StepGetCompatibleVideoEncoderConfigs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video source configurations compatible with profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetCompatibleVideoSourceConfigs_Format {
            get {
                return ResourceManager.GetString("StepGetCompatibleVideoSourceConfigs_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video encoder configurations.
        /// </summary>
        internal static string StepGetEncoderSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepGetEncoderSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting media service address.
        /// </summary>
        internal static string StepGetMediaAddress_Title {
            get {
                return ResourceManager.GetString("StepGetMediaAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting media profile.
        /// </summary>
        internal static string StepGetMediaProfile_Title {
            get {
                return ResourceManager.GetString("StepGetMediaProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting media profile [token = &apos;{0}&apos;] - negative test.
        /// </summary>
        internal static string StepGetMediaProfileNegative_Format {
            get {
                return ResourceManager.GetString("StepGetMediaProfileNegative_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting media profiles.
        /// </summary>
        internal static string StepGetMediaProfiles_Title {
            get {
                return ResourceManager.GetString("StepGetMediaProfiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting metadata configuration.
        /// </summary>
        internal static string StepGetMetadataConfig_Title {
            get {
                return ResourceManager.GetString("StepGetMetadataConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting metadata configuration options for configuration [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetMetadataConfigOptions_Format {
            get {
                return ResourceManager.GetString("StepGetMetadataConfigOptions_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting metadata configurations.
        /// </summary>
        internal static string StepGetMetadataConfigs_Title {
            get {
                return ResourceManager.GetString("StepGetMetadataConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting PTZ service address.
        /// </summary>
        internal static string StepGetPTZAddress_Title {
            get {
                return ResourceManager.GetString("StepGetPTZAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting PTZ configurations.
        /// </summary>
        internal static string StepGetPTZConfigurations_Title {
            get {
                return ResourceManager.GetString("StepGetPTZConfigurations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video encoder configuration.
        /// </summary>
        internal static string StepGetVideoEncoderConfig_Title {
            get {
                return ResourceManager.GetString("StepGetVideoEncoderConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video encoder configuration options for configuration [{0}].
        /// </summary>
        internal static string StepGetVideoEncoderConfigOptions_Format {
            get {
                return ResourceManager.GetString("StepGetVideoEncoderConfigOptions_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video encoder configuration options.
        /// </summary>
        internal static string StepGetVideoEncoderConfigOptions_Title {
            get {
                return ResourceManager.GetString("StepGetVideoEncoderConfigOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video source configuration.
        /// </summary>
        internal static string StepGetVideoSourceConfig_Title {
            get {
                return ResourceManager.GetString("StepGetVideoSourceConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video source configuration options for configuration [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepGetVideoSourceConfigOptions_Format {
            get {
                return ResourceManager.GetString("StepGetVideoSourceConfigOptions_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video source configurations.
        /// </summary>
        internal static string StepGetVideoSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepGetVideoSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting video sources.
        /// </summary>
        internal static string StepGetVideoSources_Title {
            get {
                return ResourceManager.GetString("StepGetVideoSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe device - negative test.
        /// </summary>
        internal static string StepInvalidProbe_Title {
            get {
                return ResourceManager.GetString("StepInvalidProbe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe device.
        /// </summary>
        internal static string StepProbeDevice_Title {
            get {
                return ResourceManager.GetString("StepProbeDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing audio decoder configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveAudioDecoderConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveAudioDecoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing audio encoder configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveAudioEncoderConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveAudioEncoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing audio output configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveAudioOutputConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveAudioOutputConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing audio source configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveAudioSourceConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveAudioSourceConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing metadata configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveMetadataConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveMetadataConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing PTZ configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemovePTZConfig_Format {
            get {
                return ResourceManager.GetString("StepRemovePTZConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing video analythics configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveVideoAnalythicsConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveVideoAnalythicsConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing video encoder configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveVideoEncoderConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveVideoEncoderConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing video source configuration from profile [token = &apos;{0}&apos;].
        /// </summary>
        internal static string StepRemoveVideoSourceConfig_Format {
            get {
                return ResourceManager.GetString("StepRemoveVideoSourceConfig_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting audio encoder configuration.
        /// </summary>
        internal static string StepSetAudioEncoderConfig_Title {
            get {
                return ResourceManager.GetString("StepSetAudioEncoderConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting audio encoder configuration - negative test.
        /// </summary>
        internal static string StepSetAudioEncoderInvalidConfig_Title {
            get {
                return ResourceManager.GetString("StepSetAudioEncoderInvalidConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting audio source configuration.
        /// </summary>
        internal static string StepSetAudioSourceConfig_Title {
            get {
                return ResourceManager.GetString("StepSetAudioSourceConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting audio source configuration - negative test.
        /// </summary>
        internal static string StepSetAudioSourceInvalidConfig_Title {
            get {
                return ResourceManager.GetString("StepSetAudioSourceInvalidConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting metadata configuration.
        /// </summary>
        internal static string StepSetMetadataConfig_Title {
            get {
                return ResourceManager.GetString("StepSetMetadataConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting metadata configuration - negative test.
        /// </summary>
        internal static string StepSetMetadataInvalidConfig_Title {
            get {
                return ResourceManager.GetString("StepSetMetadataInvalidConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting video encoder configuration.
        /// </summary>
        internal static string StepSetVideoEncoderConfig_Title {
            get {
                return ResourceManager.GetString("StepSetVideoEncoderConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting video encoder configuration - negative test.
        /// </summary>
        internal static string StepSetVideoEncoderInvalidConfig_Title {
            get {
                return ResourceManager.GetString("StepSetVideoEncoderInvalidConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting video source configuration.
        /// </summary>
        internal static string StepSetVideoSourceConfig_Title {
            get {
                return ResourceManager.GetString("StepSetVideoSourceConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting video source configuration - negative test.
        /// </summary>
        internal static string StepSetVideoSourceInvalidConfig_Title {
            get {
                return ResourceManager.GetString("StepSetVideoSourceInvalidConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating generic space.
        /// </summary>
        internal static string StepValidateGenericSpace {
            get {
                return ResourceManager.GetString("StepValidateGenericSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating GetConfigurations response.
        /// </summary>
        internal static string StepValidateGetConfigurations_Title {
            get {
                return ResourceManager.GetString("StepValidateGetConfigurations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating GetNodes response.
        /// </summary>
        internal static string StepValidateGetNodes_Title {
            get {
                return ResourceManager.GetString("StepValidateGetNodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating SOAP fault message.
        /// </summary>
        internal static string StepValidateMatchRuleFault {
            get {
                return ResourceManager.GetString("StepValidateMatchRuleFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating new PTZ configuration.
        /// </summary>
        internal static string StepValidateNewPTZConfig_Title {
            get {
                return ResourceManager.GetString("StepValidateNewPTZConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate probe match.
        /// </summary>
        internal static string StepValidateProbeMatch_Title {
            get {
                return ResourceManager.GetString("StepValidateProbeMatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ configuration.
        /// </summary>
        internal static string StepValidatePTZConfig_Title {
            get {
                return ResourceManager.GetString("StepValidatePTZConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ configuration options.
        /// </summary>
        internal static string StepValidatePTZConfigOptions_Title {
            get {
                return ResourceManager.GetString("StepValidatePTZConfigOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ node.
        /// </summary>
        internal static string StepValidatePTZNode_Title {
            get {
                return ResourceManager.GetString("StepValidatePTZNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ nodes.
        /// </summary>
        internal static string StepValidatePTZNodes_Title {
            get {
                return ResourceManager.GetString("StepValidatePTZNodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ profile.
        /// </summary>
        internal static string StepValidatePTZProfile {
            get {
                return ResourceManager.GetString("StepValidatePTZProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating PTZ status.
        /// </summary>
        internal static string StepValidatePTZStatus {
            get {
                return ResourceManager.GetString("StepValidatePTZStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating audio encoder configurations.
        /// </summary>
        internal static string StepValidatingAudioEncoders_Title {
            get {
                return ResourceManager.GetString("StepValidatingAudioEncoders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating audio sources.
        /// </summary>
        internal static string StepValidatingAudioSources_Title {
            get {
                return ResourceManager.GetString("StepValidatingAudioSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating metadata configurations.
        /// </summary>
        internal static string StepValidatingMetadataConfigs_Title {
            get {
                return ResourceManager.GetString("StepValidatingMetadataConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate new media profile.
        /// </summary>
        internal static string StepValidatingNewProfile_Title {
            get {
                return ResourceManager.GetString("StepValidatingNewProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating media profiles.
        /// </summary>
        internal static string StepValidatingProfiles_Title {
            get {
                return ResourceManager.GetString("StepValidatingProfiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media profile [token = &apos;{0}&apos;] contains both video source and video encoder configurations.
        /// </summary>
        internal static string StepValidatingProfilesDetails_Format {
            get {
                return ResourceManager.GetString("StepValidatingProfilesDetails_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating video encoder configuration options.
        /// </summary>
        internal static string StepValidatingVideoEncoderConfigOptions_Title {
            get {
                return ResourceManager.GetString("StepValidatingVideoEncoderConfigOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating video encoder configurations.
        /// </summary>
        internal static string StepValidatingVideoEncoderConfigs_Title {
            get {
                return ResourceManager.GetString("StepValidatingVideoEncoderConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating video source configurations.
        /// </summary>
        internal static string StepValidatingVideoSourceConfigs_Title {
            get {
                return ResourceManager.GetString("StepValidatingVideoSourceConfigs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating video sources.
        /// </summary>
        internal static string StepValidatingVideoSources_Title {
            get {
                return ResourceManager.GetString("StepValidatingVideoSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Bye message from the DUT.
        /// </summary>
        internal static string StepWaitBye_Title {
            get {
                return ResourceManager.GetString("StepWaitBye_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Bye or Hello message from the DUT.
        /// </summary>
        internal static string StepWaitByeOrHello_Title {
            get {
                return ResourceManager.GetString("StepWaitByeOrHello_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Hello message from the DUT.
        /// </summary>
        internal static string StepWaitHello_Title {
            get {
                return ResourceManager.GetString("StepWaitHello_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device to reboot.
        /// </summary>
        internal static string StepWaitReboot_Title {
            get {
                return ResourceManager.GetString("StepWaitReboot_Title", resourceCulture);
            }
        }
    }
}
