using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TestTool.Tests.Definitions.Enums
{
    /// <summary>
    /// Functionality for profile definitions
    /// </summary>
    public enum Functionality
    {
        GetCapabilities,
        GetServices,
        GetWsdlUrl,
        GetDeviceServiceCapabilities,
        GetEventsServiceCapabilities,
        GetMediaServiceCapabilities,
        GetPTZServiceCapabilities,
        GetReceiverServiceCapabilities,
        GetReplayServiceCapabilities,
        GetRecordingServiceCapabilities,
        GetSearchServiceCapabilities,
        WSDiscovery,
        GetDiscoveryMode,
        SetDiscoveryMode,
        GetHostname,
        SetHostname,
        GetDns,
        SetDns,
        GetNetworkInterfaces,
        SetNetworkInterfaces,
        GetNetworkProtocols,
        SetNetworkProtocols,
        GetNetworkDefaultGateway,
        SetNetworkDefaultGateway,
        GetDeviceInformation,
        GetSystemLog,
        GetSystemDateAndTime,
        SetSystemDateAndTime,
        SetSystemFactoryDefaults,
        Reboot,
        GetScopes,
        SetScopes,
        AddScopes,
        RemoveScopes,
        GetUsers,
        CreateUsers,
        DeleteUsers,
        SetUser,
        Notify,
        Subscribe,
        Renew,
        Unsubscribe,
        EventsSetSynchronizationPoint,
        CreatePullPointSubscription,
        PullMessages,
        GetEventProperties,
        TopicFilter,
        MessageContentFilter,
        GetNTP,
        SetNTP,
        GetDynamicDNS,
        SetDynamicDNS,
        GetZeroConfiguration,
        SetZeroConfiguration,
        GetIPAddressFilter,
        SetIPAddressFilter,
        AddIPAddressFilter,
        RemoveIPAddressFilter,
        WsSecurity, /*UsernameToken Authentication*/
        DigestAuthentication,
        CreateProfile,
        DeleteProfile,
        GetProfiles,
        GetProfile,
        MediaSetSynchronizationPoint,
        GetStreamUri,
        MediaStreamingRtsp,
        MediaStreamingRtspJpegHeaderExtension,
        GetSnapshotUri,
        HttpGetSnapshot,
        GetVideoSources,
        GetVideoSourceConfiguration,
        GetVideoSourceConfigurations,
        AddVideoSourceConfiguration,
        RemoveVideoSourceConfiguration,
        SetVideoSourceConfiguration,
        GetCompatibleVideoSourceConfigurations,
        GetVideoSourceConfigurationOptions,
        GetVideoEncoderConfiguration,
        GetVideoEncoderConfigurations,
        AddVideoEncoderConfiguration,
        RemoveVideoEncoderConfiguration,
        SetVideoEncoderConfiguration,
        GetCompatibleVideoEncoderConfigurations,
        GetVideoEncoderConfigurationOptions,
        GetGuaranteedNumberOfVideoEncoderInstances,
        GetMetadataConfiguration,
        GetMetadataConfigurations,
        AddMetadataConfiguration,
        RemoveMetadataConfiguration,
        SetMetadataConfiguration,
        GetCompatibleMetadataConfigurations,
        GetMetadataConfigurationOptions,
        StartMulticastStreaming,
        StopMulticastStreaming,
        AddPTZConfiguration,
        RemovePTZConfiguration,
        PtzGetNodes,
        PtzGetNode,
        GetPtzConfigurations,
        GetPtzConfiguration,
        GetPtzConfigurationOptions,
        SetPtzConfiguration,
        PtzContinuousMove,
        PtzStop,
        PtzGetStatus,
        PtzSetPreset,
        PtzGetPreset,
        PtzGotoPreset,
        PtzRemovePreset,
        GotoHomePosition,
        SetHomePosition,
        PtzAbsoluteMove,
        PtzRelativeMove,
        SendAuxiliaryCommand,
        GetAudioSources,
        GetAudioSourceConfiguration,
        GetAudioSourceConfigurations,
        AddAudioSourceConfiguration,
        RemoveAudioSourceConfiguration,
        SetAudioSourceConfiguration,
        SetAudioOutputConfiguration,
        GetCompatibleAudioSourceConfigurations,
        GetAudioSourceConfigurationOptions,
        GetAudioEncoderConfiguration,
        GetAudioEncoderConfigurations,
        AddAudioEncoderConfiguration,
        RemoveAudioEncoderConfiguration,
        SetAudioEncoderConfiguration,
        GetCompatibleAudioEncoderConfigurations,
        GetAudioEncoderConfigurationOptions,
        GetRelayOutputs,
        SetRelayOutputSettings,
        SetRelayOutputState,
        /* Recording search */
        GetRecordingSummary,
        GetRecordingInformation,
        GetMediaAttributes,
        FindRecordings,
        GetRecordingSearchResults,
        FindEvents,
        GetEventSearchResults,
        EndSearch,
        RecordingStateEvent, /*Recording/State Event*/
        TrackStateEvent, /*Track/State Event*/
        XPathDialect,
        /* Replay Control */ 
        ReverseReplay,
        ReplayUsingRTSP,
        GetReplayUri,
        SetReplayConfiguration,
        GetReplayConfiguration,
        /*	Recording Control */
        GetRecordings,
        SetRecordingConfiguration,
        GetRecordingConfiguration,
        GetTrackConfiguration,
        SetTrackConfiguration,
        CreateRecordingJob,
        DeleteRecordingJob,
        GetRecordingJobs,
        SetRecordingJobConfiguration,
        GetRecordingJobConfiguration,
        SetRecordingJobMode,
        GetRecordingJobState,
        RecordingJobStateChangeEvent,
        ConfigurationChangeEvent,
        DataDeletionEvent,
        /* Recording Control – Dynamic Recording */
        DeleteRecording,
        RecordingCreationDeletionEvent, // RecordingCreation/Deletion Event
        CreateTrack,
        DeleteTrack,
        TrackCreationDeletionEvent, // TrackCreation/Deletion Event
        /*Recording Search – Metadata Search*/
        FindMetadata,
	    GetMetadataSearchResults,
        /*Recording Search – PTZ Position Search*/
        FindPTZPosition,
	    GetPTZPositionSearchResults,
        /* Receiver Configuration */
        GetReceivers,
        GetReceiver,
        CreateReceiver,
        DeleteReceiver,
        ConfigureReceiver,
        SetReceiverMode,
        SetReceiverState,
        ChangeStateEvent, // ChangeState Event
        ConnectionFailedEvent, // ConnectionFailed Event







    }
}
