//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using DUT.PACS.Simulator.Common;
// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace DUT.PACS.Simulator.Common
{


    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DUT.PACS.Simulator.ServiceAccessRules10.AccessProfileInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DUT.PACS.Simulator.ServiceAccessRules10.AccessProfile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DUT.PACS.Simulator.ServiceCredential10.CredentialInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DUT.PACS.Simulator.ServiceCredential10.Credential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
}