//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5466
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace DUT.CameraWebService.Door12
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Web.Services.WebServiceAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "DoorControlBinding", Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataEntity))]
    public abstract partial class DoorControlBinding : Base.BaseDutService
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetServiceCapabilities", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Capabilities")]
        public abstract ServiceCapabilities GetServiceCapabilities();

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfoList", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("NextStartReference")]
        public abstract string GetDoorInfoList(int Limit, [System.Xml.Serialization.XmlIgnoreAttribute()] bool LimitSpecified, string StartReference, [System.Xml.Serialization.XmlElementAttribute("DoorInfo")] out DoorInfo[] DoorInfo);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfo", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DoorInfo")]
        public abstract DoorInfo[] GetDoorInfo([System.Xml.Serialization.XmlElementAttribute("Token")] string[] Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorList", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("NextStartReference")]
        public abstract string GetDoorList(int Limit, [System.Xml.Serialization.XmlIgnoreAttribute()] bool LimitSpecified, string StartReference, [System.Xml.Serialization.XmlElementAttribute("Door")] out Door[] Door);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoors", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Door")]
        public abstract Door[] GetDoors([System.Xml.Serialization.XmlElementAttribute("Token")] string[] Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/CreateDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Token")]
        public abstract string CreateDoor(Door Door);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/SetDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void SetDoor(Door Door);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/ModifyDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void ModifyDoor(Door Door);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/DeleteDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void DeleteDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorState", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DoorState")]
        public abstract DoorState GetDoorState(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/AccessDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void AccessDoor(string Token, bool UseExtendedTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool UseExtendedTimeSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string AccessTime, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string OpenTooLongTime, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string PreAlarmTime, AccessDoorExtension Extension);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/LockDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void LockDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/UnlockDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void UnlockDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/BlockDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void BlockDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void LockDownDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownReleaseDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void LockDownReleaseDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void LockOpenDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenReleaseDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void LockOpenReleaseDoor(string Token);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onvif.org/ver10/doorcontrol/wsdl/DoubleLockDoor", RequestNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", ResponseNamespace = "http://www.onvif.org/ver10/doorcontrol/wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract void DoubleLockDoor(string Token);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class ServiceCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private uint maxLimitField;

        private uint maxDoorsField;

        private bool clientSuppliedTokenSupportedField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public ServiceCapabilities()
        {
            this.maxDoorsField = ((uint)(10));
            this.clientSuppliedTokenSupportedField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "10")]
        public uint MaxDoors
        {
            get
            {
                return this.maxDoorsField;
            }
            set
            {
                this.maxDoorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class AccessDoorExtension
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorFault
    {

        private string reasonField;

        private DoorFaultState stateField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        /// <remarks/>
        public DoorFaultState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorFaultState
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        NotInFault,

        /// <remarks/>
        FaultDetected,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorTamper
    {

        private string reasonField;

        private DoorTamperState stateField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        /// <remarks/>
        public DoorTamperState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorTamperState
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        NotInTamper,

        /// <remarks/>
        TamperDetected,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorState
    {

        private DoorPhysicalState doorPhysicalStateField;

        private bool doorPhysicalStateFieldSpecified;

        private LockPhysicalState lockPhysicalStateField;

        private bool lockPhysicalStateFieldSpecified;

        private LockPhysicalState doubleLockPhysicalStateField;

        private bool doubleLockPhysicalStateFieldSpecified;

        private DoorAlarmState alarmField;

        private bool alarmFieldSpecified;

        private DoorTamper tamperField;

        private DoorFault faultField;

        private DoorMode doorModeField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public DoorPhysicalState DoorPhysicalState
        {
            get
            {
                return this.doorPhysicalStateField;
            }
            set
            {
                this.doorPhysicalStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoorPhysicalStateSpecified
        {
            get
            {
                return this.doorPhysicalStateFieldSpecified;
            }
            set
            {
                this.doorPhysicalStateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public LockPhysicalState LockPhysicalState
        {
            get
            {
                return this.lockPhysicalStateField;
            }
            set
            {
                this.lockPhysicalStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockPhysicalStateSpecified
        {
            get
            {
                return this.lockPhysicalStateFieldSpecified;
            }
            set
            {
                this.lockPhysicalStateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public LockPhysicalState DoubleLockPhysicalState
        {
            get
            {
                return this.doubleLockPhysicalStateField;
            }
            set
            {
                this.doubleLockPhysicalStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoubleLockPhysicalStateSpecified
        {
            get
            {
                return this.doubleLockPhysicalStateFieldSpecified;
            }
            set
            {
                this.doubleLockPhysicalStateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DoorAlarmState Alarm
        {
            get
            {
                return this.alarmField;
            }
            set
            {
                this.alarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlarmSpecified
        {
            get
            {
                return this.alarmFieldSpecified;
            }
            set
            {
                this.alarmFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DoorTamper Tamper
        {
            get
            {
                return this.tamperField;
            }
            set
            {
                this.tamperField = value;
            }
        }

        /// <remarks/>
        public DoorFault Fault
        {
            get
            {
                return this.faultField;
            }
            set
            {
                this.faultField = value;
            }
        }

        /// <remarks/>
        public DoorMode DoorMode
        {
            get
            {
                return this.doorModeField;
            }
            set
            {
                this.doorModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorPhysicalState
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Open,

        /// <remarks/>
        Closed,

        /// <remarks/>
        Fault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum LockPhysicalState
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Locked,

        /// <remarks/>
        Unlocked,

        /// <remarks/>
        Fault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorAlarmState
    {

        /// <remarks/>
        Normal,

        /// <remarks/>
        DoorForcedOpen,

        /// <remarks/>
        DoorOpenTooLong,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public enum DoorMode
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Locked,

        /// <remarks/>
        Unlocked,

        /// <remarks/>
        Accessed,

        /// <remarks/>
        Blocked,

        /// <remarks/>
        LockedDown,

        /// <remarks/>
        LockedOpen,

        /// <remarks/>
        DoubleLocked,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorExtension
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class TimingsExtension
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class Timings
    {

        private string releaseTimeField;

        private string openTimeField;

        private string extendedReleaseTimeField;

        private string delayTimeBeforeRelockField;

        private string extendedOpenTimeField;

        private string preAlarmTimeField;

        private TimingsExtension extensionField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string ReleaseTime
        {
            get
            {
                return this.releaseTimeField;
            }
            set
            {
                this.releaseTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string OpenTime
        {
            get
            {
                return this.openTimeField;
            }
            set
            {
                this.openTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string ExtendedReleaseTime
        {
            get
            {
                return this.extendedReleaseTimeField;
            }
            set
            {
                this.extendedReleaseTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string DelayTimeBeforeRelock
        {
            get
            {
                return this.delayTimeBeforeRelockField;
            }
            set
            {
                this.delayTimeBeforeRelockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string ExtendedOpenTime
        {
            get
            {
                return this.extendedOpenTimeField;
            }
            set
            {
                this.extendedOpenTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string PreAlarmTime
        {
            get
            {
                return this.preAlarmTimeField;
            }
            set
            {
                this.preAlarmTimeField = value;
            }
        }

        /// <remarks/>
        public TimingsExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorCapabilities
    {

        private System.Xml.XmlElement[] anyField;

        private bool accessField;

        private bool accessFieldSpecified;

        private bool accessTimingOverrideField;

        private bool accessTimingOverrideFieldSpecified;

        private bool lockField;

        private bool lockFieldSpecified;

        private bool unlockField;

        private bool unlockFieldSpecified;

        private bool blockField;

        private bool blockFieldSpecified;

        private bool doubleLockField;

        private bool doubleLockFieldSpecified;

        private bool lockDownField;

        private bool lockDownFieldSpecified;

        private bool lockOpenField;

        private bool lockOpenFieldSpecified;

        private bool doorMonitorField;

        private bool doorMonitorFieldSpecified;

        private bool lockMonitorField;

        private bool lockMonitorFieldSpecified;

        private bool doubleLockMonitorField;

        private bool doubleLockMonitorFieldSpecified;

        private bool alarmField;

        private bool alarmFieldSpecified;

        private bool tamperField;

        private bool tamperFieldSpecified;

        private bool faultField;

        private bool faultFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Access
        {
            get
            {
                return this.accessField;
            }
            set
            {
                this.accessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessSpecified
        {
            get
            {
                return this.accessFieldSpecified;
            }
            set
            {
                this.accessFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AccessTimingOverride
        {
            get
            {
                return this.accessTimingOverrideField;
            }
            set
            {
                this.accessTimingOverrideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessTimingOverrideSpecified
        {
            get
            {
                return this.accessTimingOverrideFieldSpecified;
            }
            set
            {
                this.accessTimingOverrideFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Lock
        {
            get
            {
                return this.lockField;
            }
            set
            {
                this.lockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockSpecified
        {
            get
            {
                return this.lockFieldSpecified;
            }
            set
            {
                this.lockFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Unlock
        {
            get
            {
                return this.unlockField;
            }
            set
            {
                this.unlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnlockSpecified
        {
            get
            {
                return this.unlockFieldSpecified;
            }
            set
            {
                this.unlockFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Block
        {
            get
            {
                return this.blockField;
            }
            set
            {
                this.blockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockSpecified
        {
            get
            {
                return this.blockFieldSpecified;
            }
            set
            {
                this.blockFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DoubleLock
        {
            get
            {
                return this.doubleLockField;
            }
            set
            {
                this.doubleLockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoubleLockSpecified
        {
            get
            {
                return this.doubleLockFieldSpecified;
            }
            set
            {
                this.doubleLockFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool LockDown
        {
            get
            {
                return this.lockDownField;
            }
            set
            {
                this.lockDownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockDownSpecified
        {
            get
            {
                return this.lockDownFieldSpecified;
            }
            set
            {
                this.lockDownFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool LockOpen
        {
            get
            {
                return this.lockOpenField;
            }
            set
            {
                this.lockOpenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockOpenSpecified
        {
            get
            {
                return this.lockOpenFieldSpecified;
            }
            set
            {
                this.lockOpenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DoorMonitor
        {
            get
            {
                return this.doorMonitorField;
            }
            set
            {
                this.doorMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoorMonitorSpecified
        {
            get
            {
                return this.doorMonitorFieldSpecified;
            }
            set
            {
                this.doorMonitorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool LockMonitor
        {
            get
            {
                return this.lockMonitorField;
            }
            set
            {
                this.lockMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockMonitorSpecified
        {
            get
            {
                return this.lockMonitorFieldSpecified;
            }
            set
            {
                this.lockMonitorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DoubleLockMonitor
        {
            get
            {
                return this.doubleLockMonitorField;
            }
            set
            {
                this.doubleLockMonitorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoubleLockMonitorSpecified
        {
            get
            {
                return this.doubleLockMonitorFieldSpecified;
            }
            set
            {
                this.doubleLockMonitorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Alarm
        {
            get
            {
                return this.alarmField;
            }
            set
            {
                this.alarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlarmSpecified
        {
            get
            {
                return this.alarmFieldSpecified;
            }
            set
            {
                this.alarmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Tamper
        {
            get
            {
                return this.tamperField;
            }
            set
            {
                this.tamperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TamperSpecified
        {
            get
            {
                return this.tamperFieldSpecified;
            }
            set
            {
                this.tamperFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Fault
        {
            get
            {
                return this.faultField;
            }
            set
            {
                this.faultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FaultSpecified
        {
            get
            {
                return this.faultFieldSpecified;
            }
            set
            {
                this.faultFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Door))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Door))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorInfoBase : DataEntity
    {

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Door))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class DoorInfo : DoorInfoBase
    {

        private DoorCapabilities capabilitiesField;

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public DoorCapabilities Capabilities
        {
            get
            {
                return this.capabilitiesField;
            }
            set
            {
                this.capabilitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.onvif.org/ver10/doorcontrol/wsdl")]
    public partial class Door : DoorInfo
    {

        private string doorTypeField;

        private Timings timingsField;

        private DoorExtension extensionField;

        private System.Xml.XmlAttribute[] anyAttr1Field;

        /// <remarks/>
        public string DoorType
        {
            get
            {
                return this.doorTypeField;
            }
            set
            {
                this.doorTypeField = value;
            }
        }

        /// <remarks/>
        public Timings Timings
        {
            get
            {
                return this.timingsField;
            }
            set
            {
                this.timingsField = value;
            }
        }

        /// <remarks/>
        public DoorExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr1
        {
            get
            {
                return this.anyAttr1Field;
            }
            set
            {
                this.anyAttr1Field = value;
            }
        }
    }

}