// ----------------------------------------------------------------------------
// Copyright (C) 2003-2005 Microsoft Corporation, All rights reserved.
// ----------------------------------------------------------------------------

using System;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace Microsoft.ServiceModel.Samples
{
    class UdpTestClient
    {
        static void Main(string[] args)
        {
            Console.Out.WriteLine("Testing custom Http From Imported Files Generated By SvcUtil.");

            DeviceClient client = new DeviceClient(new CustomHttpBinding(true), new EndpointAddress("http://192.168.3.144:80/onvif/device_service"));
            //DeviceClient client = new DeviceClient(new CustomHttpBinding(true), new EndpointAddress("http://localhost:27468/Dut.asmx"));

            try
            {
                HostnameInformation info = client.GetHostname();
                Console.WriteLine("HostnameInformation.Name: {0}", info.Name);

                Console.WriteLine("---------------------------------------------------");

                try
                {
                    NTPInformation ntp = client.GetNTP();
                    Console.WriteLine("NTPInformation.FromDHCP: {0}", ntp.FromDHCP);
                }
                catch (Exception exc)
                {
                    Console.WriteLine(exc.Message);
                }
                
                Console.WriteLine("OK");
                //client.BeginGetHostname(new AsyncCallback(GetHostnameCallback), client);
            }
            catch (Exception exc)
            {
                client.Abort();
                Console.WriteLine(exc.Message);
                //throw;
            }

            Console.Out.WriteLine("Press <ENTER> to complete test.");
            Console.In.ReadLine();
        }

        static void GetHostnameCallback(IAsyncResult result)
        {
            try
            {
                DeviceClient client = (DeviceClient) result.AsyncState;
                HostnameInformation info = client.EndGetHostname(result);
                Console.WriteLine("OK");

            }
            catch (Exception exc)
            {
                Console.WriteLine(exc.Message);
            }
        }
    }
}
