///////////////////////////////////////////////////////////////////////////
//!  @author        Alexander Ryltsov
////

import "oaidl.idl";
import "ocidl.idl";


import "axcore.idl";
import "devenum.idl";
import "axextend.idl";

[
  uuid(669BB843-E7C6-4bff-86A6-501BAA2D6A16),
  object
]
interface ITestControl: IUnknown
{
  //HRESULT PollLog(LPOLESTR *_filename);
  //HRESULT TrySetParameter(int* Ok);
  HRESULT ControlStream(int Control);
  //HRESULT GetCurrentStep(int* Step, int* PassBits, int* FailBits);
  //HRESULT GetStepName(int Step, LPOLESTR *StepName);
  HRESULT WaitForStableKey(double *Length);
  HRESULT WaitForSync(int *Length);
  HRESULT GetEvents(LPOLESTR *StepName);

  HRESULT GetStreamHealth(int *State);
};


[
  uuid(64AD275D-ABA6-46ef-BD69-3B24FC810196),
  helpstring("Library ONVIF RTSP Filter")
]
library ONVIFRTSPFilter
{
  [
    uuid(547D37D7-1451-414e-BF20-706F38963B16),
    helpstring("ONVIF RTSP Filter")
  ]
  coclass ONVIFRTSPFilter
  {
    [default] interface IFileSourceFilter;
    interface ITestControl;
  }

};